-----------------------------------------DATA ENGINEERING------------------------------------------

CREATE TABLE EMPLOYEES (
	EMP_NO INT PRIMARY KEY,
	EMP_TITLE_ID VARCHAR(10),
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	SEX CHAR(1) NOT NULL,
	HIRE_DATE DATE NOT NULL
);
CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR(10) PRIMARY KEY,
	DEPT_NAME VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE SALARIES (
	EMP_NO INT PRIMARY KEY,
	SALARY INT NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO)
);
CREATE TABLE TITLES (
	TITLE_ID VARCHAR(10) PRIMARY KEY,
	TITLE VARCHAR(50) NOT NULL
);
CREATE TABLE DEPT_EMP (
	EMP_NO INT,
	DEPT_NO VARCHAR(10),
	PRIMARY KEY (EMP_NO,DEPT_NO),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);
CREATE TABLE DEPT_MANAGER (
	DEPT_NO VARCHAR(10) NOT NULL,
	EMP_NO INT NOT NULL,
	PRIMARY KEY (DEPT_NO, EMP_NO),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)	
);
